openapi: 3.0.0

info:
  title: isyfomock API
  description: API for Team iSYFO sin mock
  version: 1.0.0
servers:
  - url: 'https://isyfomock.dev.intern.nav.no'
paths:
  /dialogmelding/opprett:
    post:
      operationId: opprettDialogmelding
      tags:
        - Dialogmelding
      summary: Oppretter dialogmelding til padm2
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/OpprettDialogmeldingRequest'
      responses:
        '200':
          description: Ok
        '400':
          description: Bad Request
        '500':
          description: Internal server error

  /aktor/hentAktorIdByFnr/{fnr}:
    get:
      tags:
        - Aktør
      summary: Finn aktør-ID fra fnr
      operationId: getAktorIdByFnr
      parameters:
        - name: fnr
          in: path
          description: Fødselsnummer
          required: true
      responses:
        "200":
          description: Successful operation
        "404":
          description: User not found

  /aktor/hentFnrByAktorId/{aktorId}:
    get:
      tags:
        - Aktør
      summary: Finn fnr fra aktør-ID
      operationId: getFnrByAktorId
      parameters:
        - name: aktorId
          in: path
          description: Aktør-ID
          required: true
      responses:
        "200":
          description: successful operation
        "404":
          description: User not found

  /motebehov/slett/{fnr}:
    delete:
      operationId: slettSvarMotebehov
      parameters:
        - name: fnr
          in: path
          description: Fødselsnummer
          required: true
      tags:
        - Motebehov
      summary: Slett svar motebehov
      responses:
        "200":
          description: Successful operation
        "404":
          description: User not found

  /oppfolgingsplan/slett/arbeidstaker/{fnr}:
    delete:
      operationId: slettOppfolgingsplan
      parameters:
        - name: fnr
          in: path
          description: Fødselsnummer
          required: true
      tags:
        - Oppfølgingsplan
      summary: Slett oppfolgingsplan knyttet til fødselsnummer
      responses:
        "200":
          description: Successful operation
        "404":
          description: User not found

  /oppfolgingsplan/slett/{id}:
    delete:
      operationId: slettOppfolgingsplan
      parameters:
        - name: id
          in: path
          description: Oppfølgingsplan ID
          required: true
      tags:
        - Oppfølgingsplan
      summary: Slett oppfolgingsplan med id
      responses:
        "200":
          description: Successful operation
        "404":
          description: User not found

components:
  schemas:
    OpprettDialogmeldingRequest:
      type: object
      properties:
        type:
          type: string
          description: Type dialogmelding
          enum:
            - VANLIG
            - VEDLEGG
            - SVAR_MOTEINNKALLING
            - SVAR_FORESPORSEL
            - SVAR_FORESPORSEL_VEDLEGG
        pasientFnr:
          type: string
          description: Fødselsnummer til pasient
        legeFnr:
          type: string
          description: Fødselsnummer til lege
          example: '01117302624'
        notat:
          description: Notat
          type: string
        refToParent:
          description: Referanse til forrige melding i dialogen
          type: string
        refToConversation:
          description: Referanse til start-meldingen i dialogen
          type: string
        partnerId:
          description: PartnerId for å identifisere kontoret meldingen sendes fra
          type: string
      required:
        - type
        - pasientFnr
        - legeFnr
