openapi: 3.0.0

info:
  title: isyfomock API
  description: API for Team iSYFO sin mock
  version: 1.0.0
servers:
  - url: 'https://isyfomock.intern.dev.nav.no'
paths:
  /dialogmelding/opprett:
    post:
      operationId: opprettDialogmelding
      tags:
        - Dialogmelding
      summary: Oppretter dialogmelding til padm2
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/OpprettDialogmeldingRequest'
      responses:
        '200':
          description: Ok
        '400':
          description: Bad Request
        '500':
          description: Internal server error

  /apprec/opprett:
    post:
      operationId: opprettApprec
      tags:
        - Apprec
      summary: Oppretter apprec for en dialogmelding
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/OpprettApprecRequest'
      responses:
        '200':
          description: Ok
        '400':
          description: Bad Request
        '500':
          description: Internal server error

  /aktor/hentAktorIdByFnr/{fnr}:
    get:
      tags:
        - Aktør
      summary: Finn aktør-ID fra fnr
      operationId: getAktorIdByFnr
      parameters:
        - name: fnr
          in: path
          description: Fødselsnummer
          required: true
      responses:
        "200":
          description: Successful operation
        "404":
          description: User not found

  /aktor/hentFnrByAktorId/{aktorId}:
    get:
      tags:
        - Aktør
      summary: Finn fnr fra aktør-ID
      operationId: getFnrByAktorId
      parameters:
        - name: aktorId
          in: path
          description: Aktør-ID
          required: true
      responses:
        "200":
          description: successful operation
        "404":
          description: User not found

  /motebehov/slett/{fnr}:
    delete:
      operationId: slettSvarMotebehov
      parameters:
        - name: fnr
          in: path
          description: Fødselsnummer
          required: true
      tags:
        - Motebehov
      summary: Slett svar motebehov
      responses:
        "200":
          description: Successful operation
        "404":
          description: User not found

  /oppfolgingsplan/slett/arbeidstaker/{fnr}:
    delete:
      operationId: slettOppfolgingsplan
      parameters:
        - name: fnr
          in: path
          description: Fødselsnummer
          required: true
      tags:
        - Oppfølgingsplan
      summary: Slett oppfolgingsplan knyttet til fødselsnummer
      responses:
        "200":
          description: Successful operation
        "404":
          description: User not found

  /oppfolgingsplan/slett/{id}:
    delete:
      operationId: slettOppfolgingsplan
      parameters:
        - name: id
          in: path
          description: Oppfølgingsplan ID
          required: true
      tags:
        - Oppfølgingsplan
      summary: Slett oppfolgingsplan med id
      responses:
        "200":
          description: Successful operation
        "404":
          description: User not found

  /esyfovarsel/arbeidsgiver/send:
    post:
      operationId: sendVarsel
      tags:
        - Esyfovarsel
      summary: Sender varsel til nærmeste leder via Esyfovarsel
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/EsyfovarselNarmesteLederHendelseRequest'
      responses:
        '200':
          description: Ok
        '400':
          description: Bad Request
        '500':
          description: Internal server error

  /esyfovarsel/arbeidstaker/send:
    post:
      operationId: sendVarsel
      tags:
        - Esyfovarsel
      summary: Sender varsel til arbeidstaker via Esyfovarsel
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/EsyfovarselArbeidstakerHendelseRequest'
      responses:
        '200':
          description: Ok
        '400':
          description: Bad Request
        '500':
          description: Internal server error

  /senoppfolging/svar:
    post:
      operationId: senOppfolgingSvar
      tags:
        - Meroppfølging
      summary: Sender svar på sen oppfølging på Kafka til Modia
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SenOppfolgingSvarRequest'
      responses:
        '200':
          description: Ok
        '400':
          description: Bad Request
        '500':
          description: Internal server error

  /reset/{fnr}:
    post:
      operationId: resetTestdata
      parameters:
        - name: fnr
          in: path
          description: Fødselsnummer
          required: true
      tags:
        - Reset testdata
      summary: Sender en kafkamelding til reset-topic. Apper som leser reset-topic sletter testdata knyttet til brukeren.
      responses:
        "200":
          description: Successful operation

components:
  schemas:
    OpprettDialogmeldingRequest:
      type: object
      properties:
        type:
          type: string
          description: Type dialogmelding
          enum:
            - VANLIG
            - VEDLEGG
            - SVAR_MOTEINNKALLING
            - SVAR_FORESPORSEL
            - SVAR_FORESPORSEL_VEDLEGG
        pasientFnr:
          type: string
          description: Fødselsnummer til pasient
        legeFnr:
          type: string
          description: Fødselsnummer til lege
          example: '01117302624'
        notat:
          description: Notat
          type: string
        refToParent:
          description: Referanse til forrige melding i dialogen
          type: string
        refToConversation:
          description: Referanse til start-meldingen i dialogen
          type: string
        partnerId:
          description: PartnerId for å identifisere kontoret meldingen sendes fra
          type: string
          example: '123'
      required:
        - type
        - pasientFnr
        - legeFnr
        - partnerId

    OpprettApprecRequest:
      type: object
      properties:
        status:
          type: string
          description: status
          enum:
            - OK
            - AVVIST
        errorCode:
          type: string
          description: errorCode
          example: E21
        errorText:
          type: string
          description: errorText
          example: Mottaker finnes ikke
        msgId:
          type: string
          description: msgId for sendt dialogmelding, må være gyldig uuid
      required:
        - status
        - msgId

    EsyfovarselNarmesteLederHendelseRequest:
      type: object
      properties:
        type:
          type: string
          enum:
            - NL_OPPFOLGINGSPLAN_SENDT_TIL_GODKJENNING
            - NL_DIALOGMOTE_SVAR_MOTEBEHOV
            - NL_DIALOGMOTE_MOTEBEHOV_TILBAKEMELDING
            - NL_DIALOGMOTE_INNKALT
            - NL_DIALOGMOTE_AVLYST
            - NL_DIALOGMOTE_REFERAT
            - NL_DIALOGMOTE_NYTT_TID_STED
        ferdigstill:
          type: boolean
          description: settes til true når varsel skal ferdigstilles
        data:
          type: object
          description: ekstra data som noen varseltyper krever
          example:
            tilbakemelding: Vi har vurdert at det ikke trengs møte akkurat nå
        narmesteLederFnr:
          type: string
          description: fødselsnummer til nærmeste leder som skal varsles
        arbeidstakerFnr:
          type: string
          description: fødselsnummer til arbeidstakeren varselet gjelder for
        orgnummer:
          type: string
          description: orgnummer som nærmeste leder og arbeidstaker arbeider ved
      required:
        - type
        - narmesteLederFnr
        - arbeidstakerFnr
        - orgnummer

    EsyfovarselArbeidstakerHendelseRequest:
      type: object
      properties:
        type:
          type: string
          enum:
            - SM_OPPFOLGINGSPLAN_SENDT_TIL_GODKJENNING
            - SM_DIALOGMOTE_SVAR_MOTEBEHOV
            - SM_DIALOGMOTE_MOTEBEHOV_TILBAKEMELDING
            - SM_MER_VEILEDNING
            - SM_DIALOGMOTE_INNKALT
            - SM_DIALOGMOTE_AVLYST
            - SM_DIALOGMOTE_REFERAT
            - SM_DIALOGMOTE_NYTT_TID_STED
            - SM_DIALOGMOTE_LEST
        ferdigstill:
          type: boolean
          description: settes til true når varsel skal ferdigstilles
        data:
          type: object
          description: ekstra data som noen varseltyper krever
          example:
            tilbakemelding: Vi har vurdert at det ikke trengs møte akkurat nå
        arbeidstakerFnr:
          type: string
          description: fødselsnummer til arbeidstakeren varselet gjelder for
        orgnummer:
          type: string
          description: orgnummer som nærmeste leder og arbeidstaker arbeider ved
      required:
        - type
        - arbeidstakerFnr

    SenOppfolgingSvarRequest:
      type: object
      properties:
        personIdent:
          type: string
          description: fnr til den sykmeldte
        varselId:
          description: valgfri referanse til varsel det svares på
          type: string
        response:
          type: array
          description: svarene til den sykmeldte på sen oppfølging-skjema
          items:
            type: object
            properties:
              questionType:
                type: String
              questionText:
                type: String
              answerType:
                type: String
              answerText:
                type: String
          example: [
            {
              "questionType": "FREMTIDIG_SITUASJON",
              "questionText": "I hvilken situasjon ser du for deg at du står når sykepengene tar slutt?",
              "answerType": "TILBAKE_HOS_ARBEIDSGIVER",
              "answerText": "Jeg er frisk og tilbake hos arbeidsgiver"
            },
            {
              "questionType": "BEHOV_FOR_OPPFOLGING",
              "questionText": "Har du behov for hjelp fra oss i NAV?",
              "answerType": "JA",
              "answerText": "Ja, jeg vil snakke med en veileder i NAV"
            }
          ]
      required:
        - personIdent
        - response
