apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: isyfomock
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 20
    timeout: 60
  readiness:
    path: /internal/is_ready
    initialDelay: 20
    timeout: 60
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  ingresses:
    - "https://isyfomock.intern.dev.nav.no"
  azure:
    application:
      enabled: true
  kafka:
    pool: nav-dev
  accessPolicy:
    outbound:
      external:
        - host: "b27apvl221.preprod.local"
          ports:
            - name: MQ
              port: 1413
              protocol: TCP
        - host: "syfomotebehov.dev-fss-pub.nais.io"
        - host: "syfooppfolgingsplanservice.dev-fss-pub.nais.io"
        - host: "pdl-api.dev-fss-pub.nais.io"
  envFrom:
    - secret: isyfomock-serviceuser
  env:
    - name: MQGATEWAY_HOSTNAME
      value: b27apvl221.preprod.local
    - name: MQGATEWAY_PORT
      value: '1413'
    - name: MQGATEWAY_NAME
      value: MQLS03
    - name: MQGATEWAY_CHANNEL_NAME
      value: Q1_ISYFOMOCK
    - name: PADM2_QUEUENAME
      value: QA.Q1_PADM.INPUT
    - name: APPREC_MQGATEWAY_NAME
      value: MQLS03
    - name: APPREC_MQGATEWAY_HOSTNAME
      value: b27apvl221.preprod.local
    - name: APPREC_MQGATEWAY_CHANNEL_NAME
      value: Q1_ISYFOMOCK
    - name: APPREC_MQGATEWAY_PORT
      value: '1413'
    - name: APPREC_QUEUENAME
      value: QA.Q1_ISDIALOGMELDING.IU03_UTSENDING_REPLY
    - name: PDL_CLIENT_ID
      value: "dev-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.dev-fss-pub.nais.io/graphql"
    - name: MOTEBEHOV_URL
      value: "https://syfomotebehov.dev-fss-pub.nais.io/syfomotebehov"
    - name: OPPFOLGINGSPLAN_URL
      value: "https://syfooppfolgingsplanservice.dev-fss-pub.nais.io/syfooppfolgingsplanservice"
