apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: isyfomock
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 20
    timeout: 60
  readiness:
    path: /internal/is_ready
    initialDelay: 20
    timeout: 60
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  ingresses:
    - "https://isyfomock.dev.intern.nav.no"
  azure:
    application:
      enabled: true
  envFrom:
    - secret: isyfomock-serviceuser
  env:
    - name: MQGATEWAY_HOSTNAME
      value: b27apvl221.preprod.local
    - name: MQGATEWAY_PORT
      value: '1413'
    - name: MQGATEWAY_NAME
      value: MQLS03
    - name: MQGATEWAY_CHANNEL_NAME
      value: Q1_ISYFOMOCK
    - name: PADM2_QUEUENAME
      value: QA.Q1_PADM.INPUT
    - name: PDL_CLIENT_ID
      value: "dev-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.dev-fss-pub.nais.io/graphql"