apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: testdata-reset
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  pool: nav-dev
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 2
    retentionBytes: -1
    retentionHours: 72
  acl:
    - team: team-esyfo
      application: syfomotebehov
      access: read
    - team: teamsykefravr
      application: isyfomock
      access: write