name: Deploy to dev-gcp

on:
  workflow_dispatch:
    inputs:
      gitCommit:
        description: "Complete git commit to deploy"
        required: true
        default: ""


jobs:
  deploy-dev:
    name: Deploy to NAIS Dev-gcp
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v4
      - uses: nais/login@v0
        id: login
        with:
          team: teamsykefravr
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
      - uses: nais/deploy/actions/deploy@v2
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/naiserator-dev.yaml
          VAR: image=${{ steps.login.outputs.registry }}/${{ github.event.repository.name }}:${{ github.event.inputs.gitCommit }}